### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by rapid99**

### CODE REVIEW

**Comment by rapid99** [comment]
The issue in detail is that on my new.html.erb, I use `<%= form_for @wiki do |f| %>` to have a form to create a new @wiki. However, when I go to /wiki/new, I get an error: 
`undefined method wikis_path for #<#<Class:0x007fc97f22f560>:0x007fc97f21d090>`

now I can bypass this error by changing the @wiki in `<%= form_for @wiki do |f| %>` to :wiki. This allows me to hit the /wiki/new page and submit a new wiki. However, since I am using :wiki instead of @wiki, nothing is actually being saved and pushed to my wiki collection.

**Comment by bdougie** [comment]
Why `create!` and not `create`? https://github.com/rapid99/Blocipedia/blob/bc1bf8ac2ee5f71a5d9d15e4d9cd7aad7ad8bb19/app/controllers/wiki_controller.rb#L18

**Comment by rapid99** [comment]
I've tried it both ways. Also tried `@wiki = Wiki.new(params[:wiki])` and `@wiki = Wiki.new(wiki_params)`. No luck either way

**Comment by bdougie** [comment]
is there an error message from your attempts? Are the params empty?

**Comment by rapid99** [comment]
The error message is always the same (`undefined method wikis_path for #<#<Class:0x007fc97f22f560>:0x007fc97f21d090>`). It seems like it has to be a routing issue since the error occurs as soon as you hit /wiki/new

**Comment by bdougie** [comment]
looks like it might be `wiki_index_path`

```
              wiki_index GET    /wiki(.:format)                wiki#index
                         POST   /wiki(.:format)                wiki#create
                new_wiki GET    /wiki/new(.:format)            wiki#new
               edit_wiki GET    /wiki/:id/edit(.:format)       wiki#edit
                    wiki GET    /wiki/:id(.:format)            wiki#show
                         PATCH  /wiki/:id(.:format)            wiki#update
                         PUT    /wiki/:id(.:format)            wiki#update
                         DELETE /wiki/:id(.:format)            wiki#destroy
                   users GET    /users(.:format)               users#index
                         POST   /users(.:format)               users#create
                new_user GET    /users/new(.:format)           users#new
               edit_user GET    /users/:id/edit(.:format)      users#edit
                    user GET    /users/:id(.:format)           users#show
                         PATCH  /users/:id(.:format)           users#update
                         PUT    /users/:id(.:format)           users#update
                         DELETE /users/:id(.:format)           users#destroy
                    root GET    /                              welcome#index
```

**Pull request closed without merging**
